apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-coworking-space
  name: backend-coworking-space
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend-coworking-space
  template:
    metadata:
      labels:
        service: backend-coworking-space
    spec:
      containers:
        - image: 785516211195.dkr.ecr.us-east-1.amazonaws.com/coworking-space-microservice:8
          name: backend-coworking-space
          imagePullPolicy: Always
          ports:
            - containerPort: 5153
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /readiness_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              memory: "1000Mi"
              cpu: "250m"
            limits:
              memory: "2000Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-config
      restartPolicy: Always
